Add missing header file fcntl.h to wcmConfig.c
This fixes a build error:
./wcmConfig.c:712: error: 'O_RDWR' undeclared (first use in this function)
./wcmConfig.c:712: error: (Each undeclared identifier is reported only once
./wcmConfig.c:712: error: for each function it appears in.)

Signed-off-by: Stefan Dirsch <sndirsch@suse.com>
Signed-off-by: Egbert Eich <eich@suse.de>
Signed-off-by: Ping Cheng <pingc@wacom.com>